### ISSUE TITLE
Build failed Runner.py sphinx_build.py Task.py

### ISSUE THREAD

**Issue by rbirkelbach** [hmgaudecker/econ-project-templates#24]
In the python branch I get the following error using a fresh anaconda (python 3) installation in Gnu/Linux Ubuntu 17.04.

I get this error in the R and Python branches. Do you know a solution? I haven't changed anything - it's a fresh clone of the econ-project-templates repository.

```

Waf: Leaving directory `/home/robert/econ-project-templates/bld'
Build failed
Traceback (most recent call last):
  File "/home/robert/econ-project-templates/.mywaflib/waflib/Runner.py", line 270, in task_status
    return tsk.runnable_status()
  File "/home/robert/econ-project-templates/.mywaflib/waflib/extras/sphinx_build.py", line 356, in runnable_status
    ret = super(sphinx_build_task, self).runnable_status()
  File "/home/robert/econ-project-templates/.mywaflib/waflib/Task.py", line 659, in runnable_status
    new_sig = self.signature()
  File "/home/robert/econ-project-templates/.mywaflib/waflib/Task.py", line 640, in signature
    self.sig_implicit_deps()
  File "/home/robert/econ-project-templates/.mywaflib/waflib/Task.py", line 799, in sig_implicit_deps
    (bld.node_deps[key], bld.raw_deps[key]) = self.scan()
  File "/home/robert/econ-project-templates/.mywaflib/waflib/extras/sphinx_build.py", line 242, in scan
    app,
TypeError: update() takes 4 positional arguments but 5 were given

WARNING: Build failed
Traceback (most recent call last):
  File "/home/robert/econ-project-templates/.mywaflib/waflib/Runner.py", line 270, in task_status
    return tsk.runnable_status()
  File "/home/robert/econ-project-templates/.mywaflib/waflib/extras/sphinx_build.py", line 356, in runnable_status
    ret = super(sphinx_build_task, self).runnable_status()
  File "/home/robert/econ-project-templates/.mywaflib/waflib/Task.py", line 659, in runnable_status
    new_sig = self.signature()
  File "/home/robert/econ-project-templates/.mywaflib/waflib/Task.py", line 640, in signature
    self.sig_implicit_deps()
  File "/home/robert/econ-project-templates/.mywaflib/waflib/Task.py", line 799, in sig_implicit_deps
    (bld.node_deps[key], bld.raw_deps[key]) = self.scan()
  File "/home/robert/econ-project-templates/.mywaflib/waflib/extras/sphinx_build.py", line 242, in scan
    app,
TypeError: update() takes 4 positional arguments but 5 were given

```

**Comment by hmgaudecker** [comment]
Thanks for the report. Could you just give me the Sphinx version?

**Comment by rbirkelbach** [comment]
Yes, I have installed version 1.6.3 according to 
`$ sphinx-quickstart
Welcome to the Sphinx 1.6.3 quickstart utility.
`
and 

```
>>> sphinx.version_info
(1, 6, 3, 'final', 0)
```

**Comment by hmgaudecker** [comment]
That will likely explain it, I suppose something has changed there. Will look into it, but that most likely won't happen before next week!

**Comment by rbirkelbach** [comment]
Okay, thank you. Do you know if/how I can downgrade my installation in the meanwhile? What was the last working version of sphinx?

**Comment by hmgaudecker** [comment]
conda install sphinx=1.5 should work, just checked that version.

**Comment by rbirkelbach** [comment]
Yes, Version 1.5 works, but for the R repository, I had to make some minor changes in other parts of the code to get it running without error messages. (See my pull request.)
