### ISSUE TITLE
bld/project_paths.py is not created

### ISSUE THREAD

**Issue by Eric-Sommer** [hmgaudecker/econ-project-templates#55]
After cleaning waf, `bld.project_paths` is not re-created.
After running 
``python waf.py distclean ``    
``python waf.py configure`` 

`python waf.py build` fails. This is not due to setting `$PATH` or `$PYTHONPATH` wrongly, the file is just not there.
What might be causing this?

**Comment by hmgaudecker** [comment]
What does the ``bld`` - function look like in your main wscript file? Can you just post that here?

**Comment by Eric-Sommer** [comment]
assuming you mean the `build` function:

```
def build(ctx):
    ctx.env.PROJECT_PATHS = set_project_paths(ctx)
    ctx.path_to = path_to
    # Generate header file(s) with project paths in "bld" directory
    ctx(features="write_project_paths", target="project_paths.py")
    ctx.add_group()
    ctx.recurse("src")
```

**Comment by hmgaudecker** [comment]
I did, thanks. 

> assuming you mean the `build` function:

I did, thanks. Looks alright.

What is the output of python waf.py build?

**Comment by Eric-Sommer** [comment]
```
Waf: Entering directory `W:\izamod\izadynmod\bld'
Traceback (most recent call last):
  File "W:\izamod\izadynmod\.mywaflib\waflib\Scripting.py", line 158, in waf_entry_point
    run_commands()
  File "W:\izamod\izadynmod\.mywaflib\waflib\Scripting.py", line 251, in run_commands
    ctx = run_command(cmd_name)
  File "W:\izamod\izadynmod\.mywaflib\waflib\Scripting.py", line 235, in run_command
    ctx.execute()
  File "W:\izamod\izadynmod\.mywaflib\waflib\Scripting.py", line 573, in execute
    return execute_method(self)
  File "W:\izamod\izadynmod\.mywaflib\waflib\Build.py", line 231, in execute
    self.execute_build()
  File "W:\izamod\izadynmod\.mywaflib\waflib\Build.py", line 244, in execute_build
    self.recurse([self.run_dir])
  File "W:\izamod\izadynmod\.mywaflib\waflib\Context.py", line 286, in recurse
    user_function(self)
  File "W:\izamod\izadynmod\wscript", line 94, in build
    ctx.recurse("src")
  File "W:\izamod\izadynmod\.mywaflib\waflib\Context.py", line 286, in recurse
    user_function(self)
  File "W:\izamod\izadynmod\src\wscript", line 7, in build
    ctx.recurse("analysis")
  File "W:\izamod\izadynmod\.mywaflib\waflib\Context.py", line 280, in recurse
    wscript_module = load_module(node.abspath(), encoding=encoding)
  File "W:\izamod\izadynmod\.mywaflib\waflib\Context.py", line 672, in load_module
    exec(compile(code, path, 'exec'), module.__dict__)
  File "W:\izamod\izadynmod\src\analysis\wscript", line 3, in <module>
    from bld.project_paths import project_paths_join as ppj
ModuleNotFoundError: No module named 'bld.project_paths'
```

**Comment by hmgaudecker** [comment]
Ah... You do not need the project_paths file in wscript files -- the project_paths are attached to the build context, see the examples in the templates: http://hmgaudecker.github.io/econ-project-templates/current/python/organisation.html#usage-of-the-project-paths-within-wscript-files

To understand why it fails, see here: http://hmgaudecker.github.io/econ-project-templates/current/python/waf.html#a-closer-look-at-the-build-phase

**Comment by Eric-Sommer** [comment]
OK, thanks. The reason I imported it in the `wscript` file was to create folders for each entry in a `json` file. But calling `ctx.path_to()` within a loop didn't work anyway.

**Comment by hmgaudecker** [comment]
No reason why that should not work in a loop. But this is not the right place to discuss that; there is slack for that :-)
